//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace v2tap.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("v2tap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 [v2tap]
        ///TUNTAPAddress = 10.0.100.10
        ///TUNTAPGateway = 10.0.100.1
        ///TUNTAPNetmask = 255.255.255.0
        ///TUNTAPDNS = 114.114.114.114,114.114.115.115
        ///TUNTAPMetric = 100
        ///AutoAdapterMetric = True
        ///AutoCheckAdapter = True
        ///v2rayLoggingLevel = DEBUG
        /// 的本地化字符串。
        /// </summary>
        internal static string defaultConfig {
            get {
                return ResourceManager.GetString("defaultConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///  {
        ///    &quot;ID&quot;: &quot;918170c7-b3cc-4fa4-aac6-c763886ffed1&quot;,
        ///    &quot;Remark&quot;: &quot;HK - BandwagonHost - 1Gbps&quot;,
        ///    &quot;Address&quot;: &quot;www.baidu.com&quot;,
        ///    &quot;Port&quot;: 443,
        ///    &quot;UserID&quot;: &quot;e02d1b2d-7a22-453f-adb7-4576016df5c6&quot;,
        ///    &quot;AlterId&quot;: 0,
        ///    &quot;TransferMethod&quot;: &quot;WebSockets&quot;,
        ///    &quot;Path&quot;: &quot;/&quot;,
        ///    &quot;TLSSecure&quot;: true
        ///  }
        ///] 的本地化字符串。
        /// </summary>
        internal static string defaultServerConfig {
            get {
                return ResourceManager.GetString("defaultServerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] v2ray {
            get {
                object obj = ResourceManager.GetObject("v2ray", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
